language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - export PYTHONPATH=$PWD/dmining:$PYTHONPATH
  - nosetests ./core/tests --with-coverage --cover-package=core --cover-html --cover-erase -v

 # Coverage report
after_success:
  - coveralls