language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - export PYTHONPATH=$PWD/aliciawyy/dmining:$PYTHONPATH
  - nosetests . --with-coverage --cover-package=. --cover-html --cover-erase -v

 # Coverage report
after_success:
  - coveralls