language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install codecov codacy-coverage

script:
  - export PYTHONPATH=$PWD/aliciawyy/dmining:$PYTHONPATH
  - nosetests . --with-coverage --cover-package=. --cover-html --cover-erase -v

 # Coverage report
after_success:
  - codecov
  - export CODACY_PROJECT_TOKEN=632c1d834d504afbb0c0507d5ea906ad
  - python-codacy-coverage -r coverage.xml

